# docker-compose.yml
version: "3.9"
services:
  postgres-b:
    image: postgres:13.3
    container_name: postgres-b
    env_file:
      - ./postgres.env

  postgres-b1:
    image: postgres:13.3
    container_name: postgres-b1
    env_file:
      - ./postgres.env

  postgres-b2:
    image: postgres:13.3
    container_name: postgres-b2
    env_file:
      - ./postgres.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80:80"
    env_file:
      - ./pgadmin.env